### PR TITLE
fix(editor): fix issue where removing a property from component would not update editor state

### PR DESCRIPTION
**Pull request by danielwarke**
update `UPDATE_PROPS` reducer logic to stop merging previous component state in order to allow new state to contain fewer object keys than previous state (allow deleting of component prop)

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@danielwarke the CI failure is unrelated to your changes, seems like the CI image started using a new release of NPM but that requires a node version bump.

**Comment by Hyperkid123** [comment]
@danielwarke once https://github.com/data-driven-forms/editor/pull/21 is merged, can you rebase your PR please?

**Comment by danielwarke** [comment]
> @danielwarke once #21 is merged, can you rebase your PR please?

I'm not sure if I did that correctly, but the PR checks are passing now. If there an unnecessary commit in the PR can we just do a squash merge into main?

**Comment by Hyperkid123** [comment]
@danielwarke its OK

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
